

import { Inter } from "next/font/google";
import './globals.css';
import Header from './(components)/(header)/header';
import Sidebar from './(components)/(sidebar)/sidebar';
import styles from './page.module.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <div className={styles.container}>
          <Sidebar />
          <main className={styles.mainContent}>
          {/* <h1>Dashboard</h1> */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
